include mocha.conf

font_family                     JetBrainsMono Nerd Font Mono
font_size                       14

shell                           zsh
shell_integration               disable


disable_ligatures               yes
enable_audio_bell               no


url_style                       curly

remember_window_size            no
initial_window_width            78c
initial_window_height           23c
window_padding_width            20

cursor_shape                    block
cursor_trail                    10
cursor_blink_interval           5

background_opacity              0.80
scrollbar_handle_opacity        0
scrollbar_track_opacity         0
scrollbar_track_hover_opacity   0
confirm_os_window_close         0


repaint_delay                   8
input_delay                     3

sync_to_monitor                 no
