#######################
### Hyprland Config ###
#######################

# Monitors
source = ./modules/monitors.conf

# My Programs
source = ./modules/my_programs.conf

# Environment Variables
source = ./modules/env.conf

# Autostart
source = ./modules/autostart.conf

# Permissions
source = ./modules/permissions.conf

# Look and Feel
source = ./modules/look_and_feel.conf

# Animations
source = ./modules/animations.conf

# Window Rules
source = ./modules/window_rules.conf

# Layout
source = ./modules/layout.conf

# Misc
source = ./modules/misc.conf

# Input
source = ./modules/input.conf

# Keybinds
source = ./modules/keybinds.conf

# Windows and Workspaces
source = ./modules/windows_and_workspaces.conf