#######################
### Hyprland Config ###
#######################

# Monitors
source = ~/.config/hypr/modules/monitors.conf

# My Programs
source = ~/.config/hypr/modules/my_programs.conf

# Environment Variables
source = ~/.config/hypr/modules/env.conf

# Autostart
source = ~/.config/hypr/modules/autostart.conf

# Permissions
source = ~/.config/hypr/modules/permissions.conf

# Look and Feel
source = ~/.config/hypr/modules/look_and_feel.conf

# Animations
source = ~/.config/hypr/modules/animations.conf

# Window Rules
source = ~/.config/hypr/modules/window_rules.conf

# Layout
source = ~/.config/hypr/modules/layout.conf

# Misc
source = ~/.config/hypr/modules/misc.conf

# Input
source = ~/.config/hypr/modules/input.conf

# Keybinds
source = ~/.config/hypr/modules/keybinds.conf

# Windows and Workspaces
source = ~/.config/hypr/modules/windows_and_workspaces.conf