#######################
### Hyprland Config ###
#######################

# Monitors
source = ~/.config/hypr/monitors.conf

# My Programs
source = ~/.config/hypr/my_programs.conf

# Autostart
source = ~/.config/hypr/autostart.conf

# Permissions
source = ~/.config/hypr/permissions.conf

# Look and Feel
source = ~/.config/hypr/look_and_feel.conf

# Input
source = ~/.config/hypr/input.conf

# Keybinds
source = ~/.config/hypr/keybinds.conf

# Windows and Workspaces
source = ~/.config/hypr/windows_and_workspaces.conf