####################
### WINDOW RULES ###
####################

# Ref https://wiki.hypr.land/Configuring/Window-Rules/

windowrule {
    name = suppress-maximize-events
    match:class = .*
    suppress_event = maximize
}

windowrule {
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = 1
    match:float = 1
    match:fullscreen = 0
    match:pin = 0
    no_focus = 1
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run
    match:class = hyprland-run
    move = 20 monitor_h-120
    float = 1
}

# Waybar TUI apps floating rules
windowrule {
    name = waybar-tui-float
    match:class = ^(waybar_.*)$
    float = 1
    size = 800 500
    center = 1
}

# Waybar btop floating rule (larger)
windowrule {
    name = waybar-btop-float
    match:class = waybar_btop
    float = 1
    size = 1300 900
    center = 1
}

